version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      vite-tailwind:
        patterns:
          - "vite"
          - "@tailwindcss/*"
          - "tailwindcss"
          - "laravel-vite-plugin"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
